In [6]:
!pip install kaggle

Requirement already satisfied: kaggle in c:\users\adminpc\appdata\local\programs\python\python312\lib\site-packages (1.6.14)
Requirement already satisfied: six>=1.10 in c:\users\adminpc\appdata\local\programs\python\python312\lib\site-packages (from kaggle) (1.16.0)
Requirement already satisfied: certifi>=2023.7.22 in c:\users\adminpc\appdata\local\programs\python\python312\lib\site-packages (from kaggle) (2024.2.2)
Requirement already satisfied: python-dateutil in c:\users\adminpc\appdata\local\programs\python\python312\lib\site-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: requests in c:\users\adminpc\appdata\local\programs\python\python312\lib\site-packages (from kaggle) (2.32.2)
Requirement already satisfied: tqdm in c:\users\adminpc\appdata\local\programs\python\python312\lib\site-packages (from kaggle) (4.66.4)
Requirement already satisfied: python-slugify in c:\users\adminpc\appdata\local\programs\python\python312\lib\site-packages (from kaggle) (8.0.4)
Requirement already satisfied: urllib3 in c:\users\adminpc\appdata\local\programs\python\python312\lib\site-packages (from kaggle) (2.2.1)
Requirement already satisfied: bleach in c:\users\adminpc\appdata\local\programs\python\python312\lib\site-packages (from kaggle) (6.1.0)
Requirement already satisfied: webencodings in c:\users\adminpc\appdata\local\programs\python\python312\lib\site-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: text-unidecode>=1.3 in c:\users\adminpc\appdata\local\programs\python\python312\lib\site-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\adminpc\appdata\local\programs\python\python312\lib\site-packages (from requests->kaggle) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\adminpc\appdata\local\programs\python\python312\lib\site-packages (from requests->kaggle) (3.7)
Requirement already satisfied: colorama in c:\users\adminpc\appdata\local\programs\python\python312\lib\site-packages (from tqdm->kaggle) (0.4.6)

In [7]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\adminpc\appdata\local\programs\python\python312\lib\site-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\adminpc\appdata\local\programs\python\python312\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\adminpc\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\adminpc\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\adminpc\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in c:\users\adminpc\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [2]:
import kaggle
!kaggle datasets download ankitbansal06/retail-orders -f orders.csv

Dataset URL: https://www.kaggle.com/datasets/ankitbansal06/retail-orders
License(s): CC0-1.0
Downloading orders.csv.zip to D:\Chethan V\Jupyter projects

  0%|          | 0.00/200k [00:00<?, ?B/s]
100%|##########| 200k/200k [00:00<00:00, 252kB/s]
100%|##########| 200k/200k [00:00<00:00, 252kB/s]

In [4]:
import zipfile
zip_ref=zipfile.ZipFile('orders.csv.zip')
zip_ref.extractall()
zip_ref.close()

In [14]:
import pandas as pd
df=pd.read_csv('orders.csv', na_values=['Not Available','unknown'])
df_columns=df.columns
df.columns=df_columns.str.lower()
df.columns=df.columns.str.replace(' ','_')
df

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,30,30,3,4
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,70,90,2,4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,220,260,2,2
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,30,30,4,3
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,210,240,2,3

In [17]:
df['dis']=df['list_price']*df['discount_percent']*.01
df['sales']=df['list_price']-df['dis']
df['profit']=df['sales']-df['cost_price']

In [18]:
df.drop(columns=['list_price','cost_price','discount_percent'],inplace=True)
df

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,quantity,dis,sales,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,2,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,5,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,2,1.0,19.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,3,1.2,28.8,-1.2
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,2,3.6,86.4,16.4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,2,5.2,254.8,34.8
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,4,0.9,29.1,-0.9
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,2,7.2,232.8,22.8

In [18]:
#load the data into the sql server using replace option
!pip install sqlalchemy

Collecting sqlalchemy
  Using cached SQLAlchemy-2.0.30-cp312-cp312-win_amd64.whl.metadata (9.8 kB)
Collecting typing-extensions>=4.6.0 (from sqlalchemy)
  Using cached typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)
Collecting greenlet!=0.4.17 (from sqlalchemy)
  Using cached greenlet-3.0.3-cp312-cp312-win_amd64.whl.metadata (3.9 kB)
Downloading SQLAlchemy-2.0.30-cp312-cp312-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB 217.9 kB/s eta 0:00:10
    --------------------------------------- 0.1/2.1 MB 375.8 kB/s eta 0:00:06
   -- ------------------------------------- 0.1/2.1 MB 804.6 kB/s eta 0:00:03
   ----- ---------------------------------- 0.3/2.1 MB 1.3 MB/s eta 0:00:02
   ------- -------------------------------- 0.4/2.1 MB 1.6 MB/s eta 0:00:02
   ---------- ----------------------------- 0.5/2.1 MB 1.8 MB/s eta 0:00:01
   ------------ --------------------------- 0.7/2.1 MB 2.0 MB/s eta 0:00:01
   --------------- ------------------------ 0.8/2.1 MB 2.0 MB/s eta 0:00:01
   ------------------ --------------------- 0.9/2.1 MB 2.1 MB/s eta 0:00:01
   --------------------- ------------------ 1.1/2.1 MB 2.2 MB/s eta 0:00:01
   ----------------------- ---------------- 1.2/2.1 MB 2.3 MB/s eta 0:00:01
   -------------------------- ------------- 1.4/2.1 MB 2.4 MB/s eta 0:00:01
   ----------------------------- ---------- 1.5/2.1 MB 2.4 MB/s eta 0:00:01
   --------------------------------- ------ 1.7/2.1 MB 2.5 MB/s eta 0:00:01
   ----------------------------------- ---- 1.9/2.1 MB 2.6 MB/s eta 0:00:01
   ---------------------------------------  2.0/2.1 MB 2.7 MB/s eta 0:00:01
   ---------------------------------------  2.1/2.1 MB 2.6 MB/s eta 0:00:01
   ---------------------------------------- 2.1/2.1 MB 2.5 MB/s eta 0:00:00
Downloading greenlet-3.0.3-cp312-cp312-win_amd64.whl (293 kB)
   ---------------------------------------- 0.0/293.6 kB ? eta -:--:--
   -------------------- ------------------- 153.6/293.6 kB 4.6 MB/s eta 0:00:01
   ---------------------------------------- 293.6/293.6 kB 3.6 MB/s eta 0:00:00
Downloading typing_extensions-4.12.2-py3-none-any.whl (37 kB)
Installing collected packages: typing-extensions, greenlet, sqlalchemy
Successfully installed greenlet-3.0.3 sqlalchemy-2.0.30 typing-extensions-4.12.2

In [25]:
!pip install pyodbc

Collecting pyodbc
  Downloading pyodbc-5.1.0-cp312-cp312-win_amd64.whl.metadata (2.8 kB)
Downloading pyodbc-5.1.0-cp312-cp312-win_amd64.whl (69 kB)
   ---------------------------------------- 0.0/69.3 kB ? eta -:--:--
   ----- ---------------------------------- 10.2/69.3 kB ? eta -:--:--
   ----- ---------------------------------- 10.2/69.3 kB ? eta -:--:--
   ----------------- ---------------------- 30.7/69.3 kB 220.2 kB/s eta 0:00:01
   ---------------------------------------- 69.3/69.3 kB 378.3 kB/s eta 0:00:00
Installing collected packages: pyodbc
Successfully installed pyodbc-5.1.0

In [21]:
#load the data into sql server using replae option
import sqlalchemy as sal
import pyodbc
engine = sal.create_engine(r'mssql+pyodbc://Admin\SQLEXPRESS/master?driver=ODBC+DRIVER+17+FOR+SQL+SERVER')
conn=engine.connect()

In [23]:
#load the data into sql server using append option
df.to_sql('df_orders', con=conn, index=False, if_exists= 'append')

38